# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Parstagram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Parstagram
  
  # This pulls in the latest version of Alamofire >= 4.4 but less than 5.0.
  pod 'Alamofire'
  pod 'AlamofireImage', '~> 4.1'
#  # Add additional dependencies
#  pod 'OAuthSwift'
#  pod 'OAuthSwiftAlamofire'
  pod 'Parse'
  target 'ParstagramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ParstagramUITests' do
    # Pods for testing
  end

end
