# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fixster' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fixster
  pod "AlamofireImage"

  target 'fixsterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'fixsterUITests' do
    # Pods for testing
  end

end
