# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StockTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StockTracker
  pod 'CardParts'
  pod 'Alamofire'
  pod 'AlamofireImage', '~> 4.1'
  pod 'Parse'
  pod 'TKSubmitTransition', :git => 'https://github.com/entotsu/TKSubmitTransition.git'
  target 'StockTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StockTrackerUITests' do
    # Pods for testing
  end

end
